// @generated by scripts/sync-worker-shared.js — DO NOT EDIT.
// Edit src/shared/<name>.js instead, then run `npm run sync:worker`.

'use strict';

// Reasonix resolves its state directory in this order. Keep this module free of
// Node built-ins so the source-check id and resolver can be vendored with the
// Worker shared closure without making the Worker filesystem-aware.
const REASONIX_CLIENT = 'reasonix';
const REASONIX_SOURCE_CHECK_ID = 'reasonix-stats';

function nonEmpty(value) {
  const text = String(value ?? '').trim();
  return text || '';
}

function joinPath(platform, root, ...parts) {
  const windows = platform === 'win32';
  const separator = windows ? '\\' : '/';
  let current = nonEmpty(root);
  for (const part of parts) {
    const next = nonEmpty(part);
    if (!next) continue;
    if (!current) {
      current = next;
    } else {
      current = `${current.replace(/[\\/]+$/, '')}${separator}${next.replace(/^[\\/]+/, '')}`;
    }
  }
  return current;
}

function resolveReasonixHome({ env = {}, homeDir = '', platform = '' } = {}) {
  const stateHome = nonEmpty(env.REASONIX_STATE_HOME);
  if (stateHome) return stateHome;

  const configuredHome = nonEmpty(env.REASONIX_HOME);
  if (configuredHome) return configuredHome;

  if (platform === 'win32') {
    const appData = nonEmpty(env.APPDATA);
    return joinPath(platform, appData || joinPath(platform, homeDir, 'AppData', 'Roaming'), 'reasonix');
  }
  return joinPath(platform, homeDir, '.reasonix');
}

function resolveReasonixStatsDir(options = {}) {
  const platform = options.platform || '';
  return joinPath(platform, resolveReasonixHome(options), 'stats');
}

module.exports = {
  REASONIX_CLIENT,
  REASONIX_SOURCE_CHECK_ID,
  resolveReasonixHome,
  resolveReasonixStatsDir
};
